version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
          - v1-dependencies-
      - run: 
          command: ./gradlew resolveDependencies
          working_directory: gradle-require-dependency-compliance-plugin
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
      - run: 
          command: ./gradlew test
          working_directory: gradle-require-dependency-compliance-plugin
      - run: 
          command: ./gradlew build
          working_directory: gradle-require-dependency-compliance-plugin
      - store_artifacts:
          path: gradle-require-dependency-compliance-plugin/build/libs
      - persist_to_workspace:
          root: .
          paths: ./*
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
          - v1-dependencies-
      - run: 
          command: ./gradlew publishPlugins -Pgradle.publish.key={{ .Environment.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret={{ .Environment.GRADLE_PUBLISH_SECRET }}
          working_directory: gradle-require-dependency-compliance-plugin
workflows:
  version: 2
  build_and_analze:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master